CREATE TABLE MEMBER(
    MEMBER_NO NUMBER            NOT NULL,
    ID        VARCHAR2(30 BYTE) NOT NULL,
    PW        VARCHAR2(30 BYTE) NOT NULL,
    NAME      VARCHAR2(30 BYTE),
    PHONE     VARCHAR2(15 BYTE)
);

CREATE TABLE MEMBER_LOG(
    LOG_NO    NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    LOGIN     DATE
);

ALTER TABLE MEMBER
    ADD CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_NO);
ALTER TABLE MEMBER
    ADD CONSTRAINT MEMBER_ID_UN UNIQUE(ID);
ALTER TABLE MEMBER_LOG
    ADD CONSTRAINT MEMBER_LOG_PK PRIMARY KEY(LOG_NO);
    
ALTER TABLE MEMBER_LOG
    ADD CONSTRAINT MEMBER_LOG_MEMBER_FK FOREIGN KEY(MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO);